topics:
## Telop topic
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10

## Interactive Twist markers
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8

## External velocity commands e.g from navigation stack
- name    : external
  topic   : cmd_vel
  timeout : 0.5
  priority: 1

## Emergency Stop
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255